
DECLARE
    V_CHK_TAB   NUMBER;
    V_ERR       VARCHAR2 (1000);
    V_CNT       NUMBER (2);
BEGIN
-- TABLE: CMS_TXN_PROPERTIES
    SELECT COUNT (1)
      INTO V_CHK_TAB
      FROM ALL_OBJECTS
     WHERE     OBJECT_TYPE = 'TABLE'
           AND OWNER = 'VMSCMS'
           AND OBJECT_NAME = 'CMS_TXN_PROPERTIES_R92B2';

    IF V_CHK_TAB = 1
    THEN
        DELETE FROM
            VMSCMS.CMS_TXN_PROPERTIES
              WHERE (CTP_INST_CODE,CTP_DELIVERY_CHANNEL,CTP_TXN_CODE,CTP_MSG_TYPE,CTP_REVERSAL_CODE) IN
                (SELECT CTP_INST_CODE,CTP_DELIVERY_CHANNEL,CTP_TXN_CODE,CTP_MSG_TYPE,CTP_REVERSAL_CODE 
                   FROM VMSCMS.CMS_TXN_PROPERTIES_R92B2);

        DBMS_OUTPUT.PUT_LINE (SQL%ROWCOUNT || ' rows deleted ');
    ELSE
        DBMS_OUTPUT.PUT_LINE ('Backup Object Not Found');
    END IF;

    V_CHK_TAB := 0;

-- TABLE: CMS_ISO_REQMAPPING
    SELECT COUNT (1)
      INTO V_CHK_TAB
      FROM ALL_OBJECTS
     WHERE     OBJECT_TYPE = 'TABLE'
           AND OWNER = 'VMSCMS'
           AND OBJECT_NAME = 'CMS_ISO_REQMAPPING_R92B2';

    IF V_CHK_TAB = 1
    THEN
        DELETE FROM
            VMSCMS.CMS_ISO_REQMAPPING
              WHERE (CIR_INST_CODE,CIR_MSG_TYPE,CIR_TRAN_CDE,CIR_DELIVERY_CHANNEL,CIR_ISO_FUNC_CDE,CIR_ISO_TRAN_CDE) IN
                        (SELECT CIR_INST_CODE,CIR_MSG_TYPE,CIR_TRAN_CDE,CIR_DELIVERY_CHANNEL,CIR_ISO_FUNC_CDE,CIR_ISO_TRAN_CDE
                           FROM VMSCMS.CMS_ISO_REQMAPPING_R92B2);

        DBMS_OUTPUT.PUT_LINE (SQL%ROWCOUNT || ' rows deleted ');
    ELSE
        DBMS_OUTPUT.PUT_LINE ('Backup Object Not Found');
    END IF;

EXCEPTION
    WHEN OTHERS
    THEN
        V_ERR := SUBSTR (SQLERRM, 1, 100);
        DBMS_OUTPUT.PUT_LINE ('Main Excp ' || V_ERR);
END;
/
