CREATE TABLE VMSCMS.CMS_INST_PARAM_R91B3
AS
    SELECT *
      FROM VMSCMS.CMS_INST_PARAM
     WHERE 1 = 2;

CREATE TABLE VMSCMS.CMS_RESPONSE_MAST_R91B3
AS
    SELECT *
      FROM VMSCMS.CMS_RESPONSE_MAST
     WHERE 1 = 2;